### ISSUE TITLE
The following check is only valid on Apple silicon

### ISSUE THREAD

**Issue by Gcenx** [Zoeyrae/gshade-on-mac#3]
https://github.com/Zoeyrae/gshade-on-mac/blob/bf45e521b13e0fb38c334feb0ac5732d3f30c3bf/Gshade_on_mac.sh#L299

**Comment by Zoeyrae** [comment]
I'll work on this in a few weeks.

**Comment by Gcenx** [comment]
For the moment just ignore any issue I open, it’s mostly to keep track of things.

**Comment by Zoeyrae** [comment]
Fixed the latest push in theory.

**Comment by Gcenx** [comment]
I think that’s correct
